/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ud1.compoñentesgraficos.tarefa6;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.HeadlessException;
import javax.swing.ButtonGroup;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JRadioButton;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author alumno
 */
public class Tarefa6 extends javax.swing.JFrame {
    
    private int acumDesc;
    private int precio;
    private String nombre;

    /**
     * Creates new form Tarefa6
     */
    public Tarefa6() {
        this.acumDesc = 0;
        this.nombre = null;
        this.precio = 0;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGrupUnidades = new javax.swing.ButtonGroup();
        btnGroupAdicionais = new javax.swing.ButtonGroup();
        panelPrincipal = new javax.swing.JPanel();
        lblPeza = new javax.swing.JLabel();
        txtPeza = new javax.swing.JTextField();
        lblPrezo = new javax.swing.JLabel();
        txtPrezo = new javax.swing.JTextField();
        lblUnidadesAdq = new javax.swing.JLabel();
        rbtSin = new javax.swing.JRadioButton();
        rbt5 = new javax.swing.JRadioButton();
        rbt15 = new javax.swing.JRadioButton();
        lblDescAdic = new javax.swing.JLabel();
        chEmpregado = new javax.swing.JCheckBox();
        chClientePremium = new javax.swing.JCheckBox();
        txtArea = new javax.swing.JTextArea();
        lblResultado = new javax.swing.JLabel();
        btnNovo = new javax.swing.JButton();
        btnCalcular = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        panelPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblPeza.setText("Peza");
        panelPrincipal.add(lblPeza, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));
        panelPrincipal.add(txtPeza, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 170, -1));

        lblPrezo.setText("Prezo");
        panelPrincipal.add(lblPrezo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        txtPrezo.setMinimumSize(new java.awt.Dimension(70, 24));
        txtPrezo.setPreferredSize(new java.awt.Dimension(70, 24));
        txtPrezo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPrezoKeyTyped(evt);
            }
        });
        panelPrincipal.add(txtPrezo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, -1, -1));

        lblUnidadesAdq.setText("Unidades adquiridas");
        panelPrincipal.add(lblUnidadesAdq, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, 30));

        btnGrupUnidades.add(rbtSin);
        rbtSin.setText(" 1-10");
        panelPrincipal.add(rbtSin, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, 20));

        btnGrupUnidades.add(rbt5);
        rbt5.setText(" 11-50 (Desconto 5%)");
        rbt5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbt5ActionPerformed(evt);
            }
        });
        panelPrincipal.add(rbt5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, 20));

        btnGrupUnidades.add(rbt15);
        rbt15.setText(" >50 (Desconto 15%)");
        rbt15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbt15ActionPerformed(evt);
            }
        });
        panelPrincipal.add(rbt15, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 170, 20));

        lblDescAdic.setText("Descontos adicionais");
        panelPrincipal.add(lblDescAdic, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, 20));

        btnGroupAdicionais.add(chEmpregado);
        chEmpregado.setText(" Empregado (Desconto 10%)");
        chEmpregado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chEmpregadoActionPerformed(evt);
            }
        });
        panelPrincipal.add(chEmpregado, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, -1, 20));

        btnGroupAdicionais.add(chClientePremium);
        chClientePremium.setText(" Cliente premium (Desconto 5%)");
        panelPrincipal.add(chClientePremium, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, -1, 20));

        txtArea.setBackground(new java.awt.Color(255, 255, 102));
        txtArea.setColumns(20);
        txtArea.setRows(5);
        txtArea.setPreferredSize(new java.awt.Dimension(200, 94));
        txtArea.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtAreaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtAreaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtAreaMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                txtAreaMouseReleased(evt);
            }
        });
        txtArea.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtAreaKeyPressed(evt);
            }
        });
        panelPrincipal.add(txtArea, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 40, 250, 210));

        lblResultado.setText("Resultado do cálculo");
        panelPrincipal.add(lblResultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, -1, -1));

        btnNovo.setText("Novo cálculo");
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });
        panelPrincipal.add(btnNovo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 270, 180, -1));

        btnCalcular.setText("Calcular");
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });
        panelPrincipal.add(btnCalcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 270, 180, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 560, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbt5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbt5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbt5ActionPerformed

    private void rbt15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbt15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbt15ActionPerformed

    private void chEmpregadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chEmpregadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chEmpregadoActionPerformed

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        this.nombre = this.txtPeza.getText();
        this.precio = Integer.parseInt(this.txtPrezo.getText());
        if (this.rbt5.isSelected()) {
            this.precio -= (int) (this.precio * 0.05);
        } else if (this.rbt15.isSelected()) {
            this.precio -= (int) (this.precio * 0.15);
        }
        
        if (this.chClientePremium.isSelected()) {
            this.precio -= (int) (this.precio * 0.05);
        } else if (this.chEmpregado.isSelected()) {
            this.precio -= (int) (this.precio * 0.10);
        }
        this.txtArea.setText(this.precio + "");
    }//GEN-LAST:event_btnCalcularActionPerformed

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        this.acumDesc = 0;
        this.nombre = null;
        this.precio = 0;
        this.btnGrupUnidades.clearSelection();
        this.txtPeza.setText("");
        this.txtPrezo.setText("");
        this.btnGroupAdicionais.clearSelection();
        this.txtArea.setText("");
    }//GEN-LAST:event_btnNovoActionPerformed

    private void txtPrezoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPrezoKeyTyped

    }//GEN-LAST:event_txtPrezoKeyTyped

    private void txtAreaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAreaKeyPressed

    }//GEN-LAST:event_txtAreaKeyPressed

    private void txtAreaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtAreaMouseClicked
        

    }//GEN-LAST:event_txtAreaMouseClicked

    private void txtAreaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtAreaMouseReleased

    }//GEN-LAST:event_txtAreaMouseReleased

    private void txtAreaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtAreaMouseEntered
        this.txtArea.setEnabled(false);
        this.txtArea.setDisabledTextColor(Color.YELLOW);    }//GEN-LAST:event_txtAreaMouseEntered

    private void txtAreaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtAreaMouseExited
        this.txtArea.setEnabled(true);
     }//GEN-LAST:event_txtAreaMouseExited

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        System.exit(0);
    }//GEN-LAST:event_formWindowClosed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tarefa6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tarefa6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tarefa6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tarefa6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tarefa6().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcular;
    private javax.swing.ButtonGroup btnGroupAdicionais;
    private javax.swing.ButtonGroup btnGrupUnidades;
    private javax.swing.JButton btnNovo;
    private javax.swing.JCheckBox chClientePremium;
    private javax.swing.JCheckBox chEmpregado;
    private javax.swing.JLabel lblDescAdic;
    private javax.swing.JLabel lblPeza;
    private javax.swing.JLabel lblPrezo;
    private javax.swing.JLabel lblResultado;
    private javax.swing.JLabel lblUnidadesAdq;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JRadioButton rbt15;
    private javax.swing.JRadioButton rbt5;
    private javax.swing.JRadioButton rbtSin;
    private javax.swing.JTextArea txtArea;
    private javax.swing.JTextField txtPeza;
    private javax.swing.JTextField txtPrezo;
    // End of variables declaration//GEN-END:variables
}
