/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ud1.compoñentesgraficos.tarefa6;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.HeadlessException;
import javax.swing.ButtonGroup;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JRadioButton;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author alumno
 */
public class Tarefa6 extends javax.swing.JFrame {

    public static final double DESCUENTO_15 = 0.15;
    public static final double DESCUENTO_10 = 0.10;
    public static final double DESCUENTO_5 = 0.05;

    private int acumDesc;
    private double prezo;
    private String nome;
    private StringBuilder unir;
    private int desc;

    /**
     * Creates new form Tarefa6
     */
    public Tarefa6() {
        this.acumDesc = 0;
        this.desc = 0;
        this.unir = new StringBuilder();
        this.nome = null;
        this.prezo = 0;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGrupUnidades = new javax.swing.ButtonGroup();
        btnGroupAdicionais = new javax.swing.ButtonGroup();
        panelPrincipal = new javax.swing.JPanel();
        lblPeza = new javax.swing.JLabel();
        txtPeza = new javax.swing.JTextField();
        lblPrezo = new javax.swing.JLabel();
        txtPrezo = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        txtArea = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        chEmpregado = new javax.swing.JCheckBox();
        chClientePremium = new javax.swing.JCheckBox();
        jPanel3 = new javax.swing.JPanel();
        rbt5 = new javax.swing.JRadioButton();
        rbt15 = new javax.swing.JRadioButton();
        rbtSin = new javax.swing.JRadioButton();
        btnNovo = new javax.swing.JButton();
        btnCalcular = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        panelPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblPeza.setText("Peza");
        panelPrincipal.add(lblPeza, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        txtPeza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPezaActionPerformed(evt);
            }
        });
        panelPrincipal.add(txtPeza, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 170, -1));

        lblPrezo.setText("Prezo");
        panelPrincipal.add(lblPrezo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        txtPrezo.setMinimumSize(new java.awt.Dimension(70, 24));
        txtPrezo.setPreferredSize(new java.awt.Dimension(70, 24));
        txtPrezo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrezoActionPerformed(evt);
            }
        });
        txtPrezo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPrezoKeyTyped(evt);
            }
        });
        panelPrincipal.add(txtPrezo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, -1, -1));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Resultado do calculo"));
        jPanel1.setLayout(new java.awt.BorderLayout());

        txtArea.setBackground(new java.awt.Color(255, 255, 102));
        txtArea.setColumns(20);
        txtArea.setRows(5);
        txtArea.setPreferredSize(new java.awt.Dimension(200, 94));
        txtArea.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtAreaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtAreaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtAreaMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                txtAreaMouseReleased(evt);
            }
        });
        txtArea.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtAreaKeyPressed(evt);
            }
        });
        jPanel1.add(txtArea, java.awt.BorderLayout.CENTER);

        panelPrincipal.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, 320, 260));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Descontos Adicionais"));
        jPanel2.setMaximumSize(new java.awt.Dimension(270, 80));
        jPanel2.setMinimumSize(new java.awt.Dimension(270, 80));
        jPanel2.setLayout(new java.awt.BorderLayout());

        btnGroupAdicionais.add(chEmpregado);
        chEmpregado.setText(" Empregado (Desconto 10%)");
        chEmpregado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chEmpregadoActionPerformed(evt);
            }
        });
        jPanel2.add(chEmpregado, java.awt.BorderLayout.CENTER);

        btnGroupAdicionais.add(chClientePremium);
        chClientePremium.setText(" Cliente premium (Desconto 5%)");
        jPanel2.add(chClientePremium, java.awt.BorderLayout.PAGE_START);

        panelPrincipal.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 270, 80));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Unidades adquiridas"));
        jPanel3.setLayout(new java.awt.BorderLayout());

        btnGrupUnidades.add(rbt5);
        rbt5.setText(" 11-50 (Desconto 5%)");
        rbt5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbt5ActionPerformed(evt);
            }
        });
        jPanel3.add(rbt5, java.awt.BorderLayout.CENTER);

        btnGrupUnidades.add(rbt15);
        rbt15.setText(" >50 (Desconto 15%)");
        rbt15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbt15ActionPerformed(evt);
            }
        });
        jPanel3.add(rbt15, java.awt.BorderLayout.PAGE_END);

        btnGrupUnidades.add(rbtSin);
        rbtSin.setText(" 1-10");
        rbtSin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtSinActionPerformed(evt);
            }
        });
        jPanel3.add(rbtSin, java.awt.BorderLayout.PAGE_START);

        panelPrincipal.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 270, 90));

        btnNovo.setText("Novo cálculo");
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });

        btnCalcular.setText("Calcular");
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 645, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addComponent(btnNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCalcular, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCalcular)
                    .addComponent(btnNovo))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbt5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbt5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbt5ActionPerformed

    private void rbt15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbt15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbt15ActionPerformed

    private void chEmpregadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chEmpregadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chEmpregadoActionPerformed

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        this.unir.delete(0, unir.length());
        this.desc = 0;
        this.nome = this.txtPeza.getText();
        this.prezo = Double.parseDouble(this.txtPrezo.getText());
        this.unir.append("Peza: ").append(this.nome).append("\n");
        this.unir.append("Prezo sen descontos: ").append(this.prezo).append("\n");
        this.unir.append("Descontos aplicados").append("\n");
        this.unir.append("________________________").append("\n").append("\n");

        if (this.rbt5.isSelected()) {
            this.prezo -= this.prezo * DESCUENTO_5;
            this.desc = (int) (100 * DESCUENTO_5);
            this.unir.append("Desconto por unidades adquiridas 5%").append("\n");
        } else if (this.rbt15.isSelected()) {
            this.prezo -= this.prezo * DESCUENTO_15;
            this.desc = (int) (100 * DESCUENTO_15);

            this.unir.append("Desconto por unidades adquiridas 15%").append("\n");
        } else {
            this.unir.append("Sen desconto por unidades adquiridas").append("\n");
        }

        if (this.chClientePremium.isSelected()) {
            this.prezo -= this.prezo * DESCUENTO_5;
            this.desc += (int) (100 * DESCUENTO_5);

            this.unir.append("Desconto adicionais 5%").append("\n");

        } else if (this.chEmpregado.isSelected()) {
            this.prezo -= this.prezo * DESCUENTO_10;
            this.desc += (int) (100 * DESCUENTO_10);

            this.unir.append("Desconto adicionais 10%").append("\n");

        } else {
            this.unir.append("Sen desconto adicionais").append("\n");

        }
        if (this.prezo != Double.parseDouble(this.txtPrezo.getText())) {
            this.unir.append("Descontos total sobre o precio final ").append(this.desc).append("%").append("\n");
            this.unir.append("Prezo con descontos ").append(this.prezo).append("\n");
        } else {
            this.unir.append("Prezo sen ningun desconto ").append(this.prezo);
        }
        this.txtArea.setText(unir.toString());
    }//GEN-LAST:event_btnCalcularActionPerformed

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        this.acumDesc = 0;
        this.nome = null;
        this.prezo = 0;
        this.btnGrupUnidades.clearSelection();
        this.txtPeza.setText("");
        this.txtPrezo.setText("");
        this.btnGroupAdicionais.clearSelection();
        this.txtArea.setText("");
        this.unir.delete(0, unir.length());
        this.desc = 0;


    }//GEN-LAST:event_btnNovoActionPerformed

    private void txtPrezoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPrezoKeyTyped

    }//GEN-LAST:event_txtPrezoKeyTyped

    private void txtAreaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAreaKeyPressed

    }//GEN-LAST:event_txtAreaKeyPressed

    private void txtAreaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtAreaMouseClicked


    }//GEN-LAST:event_txtAreaMouseClicked

    private void txtAreaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtAreaMouseReleased

    }//GEN-LAST:event_txtAreaMouseReleased

    private void txtAreaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtAreaMouseEntered
        this.txtArea.setEnabled(false);
        this.txtArea.setDisabledTextColor(Color.YELLOW);    }//GEN-LAST:event_txtAreaMouseEntered

    private void txtAreaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtAreaMouseExited
        this.txtArea.setEnabled(true);
     }//GEN-LAST:event_txtAreaMouseExited

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        System.exit(0);
    }//GEN-LAST:event_formWindowClosed

    private void txtPrezoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrezoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrezoActionPerformed

    private void txtPezaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPezaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPezaActionPerformed

    private void rbtSinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtSinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtSinActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tarefa6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tarefa6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tarefa6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tarefa6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tarefa6().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcular;
    private javax.swing.ButtonGroup btnGroupAdicionais;
    private javax.swing.ButtonGroup btnGrupUnidades;
    private javax.swing.JButton btnNovo;
    private javax.swing.JCheckBox chClientePremium;
    private javax.swing.JCheckBox chEmpregado;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblPeza;
    private javax.swing.JLabel lblPrezo;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JRadioButton rbt15;
    private javax.swing.JRadioButton rbt5;
    private javax.swing.JRadioButton rbtSin;
    private javax.swing.JTextArea txtArea;
    private javax.swing.JTextField txtPeza;
    private javax.swing.JTextField txtPrezo;
    // End of variables declaration//GEN-END:variables
}
