/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package ud1.menusxanelas.aplicacionmdi;

import com.mysql.cj.xdevapi.Table;
import java.util.ArrayList;
import java.util.Arrays;
import javax.crypto.AEADBadTagException;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import ud1.Articulo;
import ud1.BBDD;
import ud1.Cliente;

/**
 *
 * @author neo
 */
public class VentanaProductosTabla extends javax.swing.JInternalFrame {

    private BBDD datos;
    private DefaultTableModel modelo;
    private VentanaProductos p;

    /**
     * Creates new form VentanaProductosTabla
     */
    public VentanaProductosTabla(BBDD datos, VentanaProductos p) {
        this.datos = datos;
        this.p = p;
        ArrayList<Articulo> data = this.datos.obtenerArticulos();
        String[] columnNames = {"Codigo", "Articulo", "Unidad", "Cantidad", "Precio",
            "Importe"};
        this.modelo = new DefaultTableModel();
        for (String col : columnNames) {
            this.modelo.addColumn(col);
        }
        for (Articulo articulo : data) {
            this.modelo.addRow(new String[]{articulo.getCodigo(), articulo.getArticulo(),
                articulo.getUnidad(), articulo.getCantidad() + "", articulo.getPrecio() + "",
                articulo.getImporte() + ""});
        }
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jTable1.setModel(this.modelo);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(7, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        String datos = (String) this.jTable1.getValueAt(this.jTable1.getSelectedRow(), 0);
        this.p.datos(datos);
        dispose();
    }//GEN-LAST:event_jTable1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
