/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ud1.layouts.tarefa7;

import java.awt.CardLayout;

/**
 *
 * @author alumno
 */
public class Tarefa7 extends javax.swing.JFrame {

    /**
     * Creates new form Tarefa7
     */
    public Tarefa7() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        panelIzquierda = new javax.swing.JPanel();
        filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 13));
        jButton1 = new javax.swing.JButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 13));
        jButton2 = new javax.swing.JButton();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 13));
        jButton3 = new javax.swing.JButton();
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 13));
        jButton4 = new javax.swing.JButton();
        filler5 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 13));
        panelCentral = new javax.swing.JPanel();
        pnlFlow = new javax.swing.JPanel();
        pnlBox = new javax.swing.JPanel();
        pnlGrid = new javax.swing.JPanel();
        pnlNull = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        panelIzquierda.setBackground(new java.awt.Color(0, 0, 0));
        panelIzquierda.setLayout(new javax.swing.BoxLayout(panelIzquierda, javax.swing.BoxLayout.PAGE_AXIS));
        panelIzquierda.add(filler4);

        jButton1.setText("FlowLayaut");
        buttonGroup1.add(jButton1);
        jButton1.setMaximumSize(new java.awt.Dimension(111, 80));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        panelIzquierda.add(jButton1);
        panelIzquierda.add(filler1);

        jButton2.setText("BoxLayout X");
        buttonGroup1.add(jButton2);
        jButton2.setMaximumSize(new java.awt.Dimension(111, 80));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        panelIzquierda.add(jButton2);
        panelIzquierda.add(filler2);

        jButton3.setText("GridLayout");
        buttonGroup1.add(jButton3);
        jButton3.setMaximumSize(new java.awt.Dimension(111, 80));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        panelIzquierda.add(jButton3);
        panelIzquierda.add(filler3);

        jButton4.setText("NullLayout");
        buttonGroup1.add(jButton4);
        jButton4.setMaximumSize(new java.awt.Dimension(111, 80));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        panelIzquierda.add(jButton4);
        panelIzquierda.add(filler5);

        getContentPane().add(panelIzquierda);

        panelCentral.setLayout(new java.awt.CardLayout());
        panelCentral.add(pnlFlow, "card2");

        pnlBox.setLayout(new javax.swing.BoxLayout(pnlBox, javax.swing.BoxLayout.LINE_AXIS));
        panelCentral.add(pnlBox, "card3");

        pnlGrid.setLayout(new java.awt.GridLayout(1, 0));
        panelCentral.add(pnlGrid, "card4");

        pnlNull.setLayout(null);
        panelCentral.add(pnlNull, "card5");

        getContentPane().add(panelCentral);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
CardLayout cardLayout = (CardLayout) this.panelCentral.getLayout();
        cardLayout.show(this.panelCentral, "card3");     }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
CardLayout cardLayout = (CardLayout) this.panelCentral.getLayout();
        cardLayout.show(this.panelCentral, "card2");     }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
CardLayout cardLayout = (CardLayout) this.panelCentral.getLayout();
        cardLayout.show(this.panelCentral, "card4");     }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
CardLayout cardLayout = (CardLayout) this.panelCentral.getLayout();
        cardLayout.show(this.panelCentral, "card5");     }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tarefa7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tarefa7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tarefa7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tarefa7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tarefa7().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler3;
    private javax.swing.Box.Filler filler4;
    private javax.swing.Box.Filler filler5;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JPanel panelCentral;
    private javax.swing.JPanel panelIzquierda;
    private javax.swing.JPanel pnlBox;
    private javax.swing.JPanel pnlFlow;
    private javax.swing.JPanel pnlGrid;
    private javax.swing.JPanel pnlNull;
    // End of variables declaration//GEN-END:variables
}
