/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package ud1.formulario_presentable;

import java.awt.CardLayout;
import java.awt.Color;
import java.util.Timer;
import java.util.TimerTask;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.prefs.BackingStoreException;
import javax.swing.ImageIcon;
import javax.swing.border.Border;
import ud1.cardlayaut.CardLayaut;

/**
 *
 * @author neo
 */
public class CrearUsuario extends javax.swing.JDialog {

    /**
     * Creates new form CrearUsuario
     *
     * @param parent
     * @param correo
     */
    public CrearUsuario(java.awt.Frame parent, String correo) {
        super(parent, true);
        initComponents();
        this.deshabilitarTodo();
        setResizable(false);
        txtCorreo.setText(correo);
        ImageIcon icon = new ImageIcon("tenor.gif");
        jLabel6.setIcon(icon);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        btnCorreo = new javax.swing.JButton();
        txtU = new javax.swing.JTextField();
        btnPass = new javax.swing.JButton();
        jPasswordField1 = new javax.swing.JPasswordField();
        txtN = new javax.swing.JTextField();
        btnUs = new javax.swing.JButton();
        btnF = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(400, 300));
        setMinimumSize(new java.awt.Dimension(400, 300));

        jPanel3.setLayout(new java.awt.CardLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(null);

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Correo");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(15, 17, 130, 17);

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Contraseña");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(15, 75, 140, 17);

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Usuario");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(15, 133, 130, 17);

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Nombre");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(15, 200, 140, 17);

        txtCorreo.setBackground(new java.awt.Color(204, 255, 204));
        jPanel1.add(txtCorreo);
        txtCorreo.setBounds(15, 40, 214, 23);

        btnCorreo.setBackground(new java.awt.Color(153, 153, 255));
        btnCorreo.setText("Validar");
        btnCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCorreoActionPerformed(evt);
            }
        });
        jPanel1.add(btnCorreo);
        btnCorreo.setBounds(241, 40, 72, 23);

        txtU.setBackground(new java.awt.Color(204, 255, 204));
        jPanel1.add(txtU);
        txtU.setBounds(15, 162, 214, 23);

        btnPass.setBackground(new java.awt.Color(153, 153, 255));
        btnPass.setText("Validar");
        btnPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPassActionPerformed(evt);
            }
        });
        jPanel1.add(btnPass);
        btnPass.setBounds(241, 98, 72, 23);

        jPasswordField1.setBackground(new java.awt.Color(204, 255, 204));
        jPanel1.add(jPasswordField1);
        jPasswordField1.setBounds(15, 98, 214, 23);

        txtN.setBackground(new java.awt.Color(204, 255, 204));
        jPanel1.add(txtN);
        txtN.setBounds(15, 223, 214, 23);

        btnUs.setBackground(new java.awt.Color(153, 153, 255));
        btnUs.setText("Validar");
        btnUs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsActionPerformed(evt);
            }
        });
        jPanel1.add(btnUs);
        btnUs.setBounds(241, 162, 72, 23);

        btnF.setBackground(new java.awt.Color(153, 153, 255));
        btnF.setText("Validar");
        btnF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFActionPerformed(evt);
            }
        });
        jPanel1.add(btnF);
        btnF.setBounds(241, 223, 72, 23);
        jPanel1.add(jLabel6);
        jLabel6.setBounds(-5, -5, 360, 280);

        jPanel3.add(jPanel1, "card2");

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("FINALIZADO CON EXITO");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addComponent(jLabel5)
                .addContainerGap(115, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addComponent(jLabel5)
                .addContainerGap(141, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel2, "card3");

        getContentPane().add(jPanel3, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCorreoActionPerformed
        // TODO add your handling code here:
        btnCorreo.setVisible(false);
        jLabel2.setVisible(true);
        btnPass.setVisible(true);
        jPasswordField1.setVisible(true);
    }//GEN-LAST:event_btnCorreoActionPerformed

    private void btnPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPassActionPerformed
        btnPass.setVisible(false);

        jLabel3.setVisible(true);
        btnUs.setVisible(true);
        txtU.setVisible(true);
    }//GEN-LAST:event_btnPassActionPerformed

    private void btnUsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsActionPerformed
        btnUs.setVisible(false);

        jLabel4.setVisible(true);
        btnF.setVisible(true);
        txtN.setVisible(true);
    }//GEN-LAST:event_btnUsActionPerformed

    private void btnFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFActionPerformed
        CardLayout paneisLayout = (CardLayout) this.jPanel3.getLayout();
        paneisLayout.show(this.jPanel3, "card3");
        Timer timer = new Timer();
        timer.schedule(new TimerTask() {
            @Override
            public void run() {
                dispose();
            }
        }, 3000);
    }//GEN-LAST:event_btnFActionPerformed

    private void deshabilitarTodo() {
        txtN.setVisible(false);
        jPasswordField1.setVisible(false);
        txtU.setVisible(false);
        btnF.setVisible(false);
        btnPass.setVisible(false);
        btnUs.setVisible(false);
        jLabel2.setVisible(false);
        jLabel3.setVisible(false);
        jLabel4.setVisible(false);
    }
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCorreo;
    private javax.swing.JButton btnF;
    private javax.swing.JButton btnPass;
    private javax.swing.JButton btnUs;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtN;
    private javax.swing.JTextField txtU;
    // End of variables declaration//GEN-END:variables

}
