package ud1.compoñentesgraficos.resumencomponentes;

import BBDD.BD;
import javax.swing.DefaultListModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author alumno
 */
public class RComponentes extends javax.swing.JFrame {

    /**
     * Creates new form RComponentes
     */
    private DefaultListModel modeloClientes;
    private BD basedatos;

    public RComponentes() {
        initComponents();
        basedatos= new BD();
        modeloClientes= new DefaultListModel();
        jList1.setModel(modeloClientes);
        modeloClientes.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelNorte = new javax.swing.JPanel();
        jLabelSingle = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListSingle = new javax.swing.JList<>();
        jButtonAceptar1 = new javax.swing.JButton();
        jLabelMultiple = new javax.swing.JLabel();
        jScrollPaneMultiple = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jButtonAceptar2 = new javax.swing.JButton();
        jPanelCentro = new javax.swing.JPanel();
        jTextAreaDatos = new javax.swing.JTextArea();
        jLabelEtiqueta = new javax.swing.JLabel();
        jPanelBotonesCentro = new javax.swing.JPanel();
        jButtonObtenerCliente = new javax.swing.JButton();
        jButtonLimpiarLista = new javax.swing.JButton();
        jButtonBorrar1Cliente = new javax.swing.JButton();
        jPanelSur = new javax.swing.JPanel();
        jLabelDNI = new javax.swing.JLabel();
        jTextFieldDNI = new javax.swing.JTextField();
        jLabelNombre = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabelDireccion = new javax.swing.JLabel();
        jTextFieldDireccion = new javax.swing.JTextField();
        jLabelTelefono = new javax.swing.JLabel();
        jTextFieldTelefono = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelNorte.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanelNorte.setOpaque(false);
        jPanelNorte.setPreferredSize(new java.awt.Dimension(852, 150));

        jLabelSingle.setText("SelectionModel = Single");

        jListSingle.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "A coruña ", "Lugo", "Ourense", "Pontevedra" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jListSingle);

        jButtonAceptar1.setText("Aceptar");

        jLabelMultiple.setText("SelectionModel = Multiple (Un JComboBox no tiene selección multiple)");

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "A coruña", "Lugo", "Ourense", "Pontevedra", "Sevilla", "Madrid", " " };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPaneMultiple.setViewportView(jList1);

        jButtonAceptar2.setText("Aceptar");

        javax.swing.GroupLayout jPanelNorteLayout = new javax.swing.GroupLayout(jPanelNorte);
        jPanelNorte.setLayout(jPanelNorteLayout);
        jPanelNorteLayout.setHorizontalGroup(
            jPanelNorteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelNorteLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanelNorteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelNorteLayout.createSequentialGroup()
                        .addComponent(jLabelSingle)
                        .addGap(139, 139, 139)
                        .addComponent(jLabelMultiple))
                    .addGroup(jPanelNorteLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonAceptar1)
                        .addGap(68, 68, 68)
                        .addComponent(jScrollPaneMultiple, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(jButtonAceptar2)))
                .addContainerGap(118, Short.MAX_VALUE))
        );
        jPanelNorteLayout.setVerticalGroup(
            jPanelNorteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelNorteLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanelNorteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelNorteLayout.createSequentialGroup()
                        .addGroup(jPanelNorteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelSingle)
                            .addComponent(jLabelMultiple))
                        .addGroup(jPanelNorteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelNorteLayout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(jButtonAceptar2))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelNorteLayout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(jButtonAceptar1)
                                .addGap(45, 45, 45))
                            .addGroup(jPanelNorteLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPaneMultiple, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanelNorte, java.awt.BorderLayout.PAGE_START);

        jPanelCentro.setMaximumSize(new java.awt.Dimension(852, 150));
        jPanelCentro.setMinimumSize(new java.awt.Dimension(852, 150));
        jPanelCentro.setPreferredSize(new java.awt.Dimension(852, 150));

        jTextAreaDatos.setColumns(20);
        jTextAreaDatos.setRows(5);

        jLabelEtiqueta.setText("Etiqueta");

        jButtonObtenerCliente.setText("ObtenerCliente");

        jButtonLimpiarLista.setText("LimpiarLista");

        jButtonBorrar1Cliente.setText("Borrar 1 Cliente");

        javax.swing.GroupLayout jPanelBotonesCentroLayout = new javax.swing.GroupLayout(jPanelBotonesCentro);
        jPanelBotonesCentro.setLayout(jPanelBotonesCentroLayout);
        jPanelBotonesCentroLayout.setHorizontalGroup(
            jPanelBotonesCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBotonesCentroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelBotonesCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonBorrar1Cliente, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                    .addComponent(jButtonLimpiarLista, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonObtenerCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(86, Short.MAX_VALUE))
        );
        jPanelBotonesCentroLayout.setVerticalGroup(
            jPanelBotonesCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBotonesCentroLayout.createSequentialGroup()
                .addComponent(jButtonObtenerCliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonLimpiarLista)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonBorrar1Cliente)
                .addContainerGap(78, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelCentroLayout = new javax.swing.GroupLayout(jPanelCentro);
        jPanelCentro.setLayout(jPanelCentroLayout);
        jPanelCentroLayout.setHorizontalGroup(
            jPanelCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCentroLayout.createSequentialGroup()
                .addGroup(jPanelCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCentroLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jTextAreaDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 591, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanelBotonesCentro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanelCentroLayout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(jLabelEtiqueta)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelCentroLayout.setVerticalGroup(
            jPanelCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCentroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelEtiqueta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelBotonesCentro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextAreaDatos))
                .addContainerGap())
        );

        getContentPane().add(jPanelCentro, java.awt.BorderLayout.CENTER);

        jPanelSur.setPreferredSize(new java.awt.Dimension(852, 150));
        jPanelSur.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelDNI.setText("DNI");
        jPanelSur.add(jLabelDNI, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, -1, -1));

        jTextFieldDNI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDNIActionPerformed(evt);
            }
        });
        jPanelSur.add(jTextFieldDNI, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, 110, -1));

        jLabelNombre.setText("Nombre");
        jPanelSur.add(jLabelNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, -1, -1));
        jPanelSur.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, 180, -1));

        jLabelDireccion.setText("Dirección");
        jPanelSur.add(jLabelDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, -1, -1));
        jPanelSur.add(jTextFieldDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, 230, -1));

        jLabelTelefono.setText("Teléfono");
        jPanelSur.add(jLabelTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, -1, -1));
        jPanelSur.add(jTextFieldTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 110, -1));

        getContentPane().add(jPanelSur, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldDNIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDNIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDNIActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RComponentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RComponentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RComponentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RComponentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RComponentes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAceptar1;
    private javax.swing.JButton jButtonAceptar2;
    private javax.swing.JButton jButtonBorrar1Cliente;
    private javax.swing.JButton jButtonLimpiarLista;
    private javax.swing.JButton jButtonObtenerCliente;
    private javax.swing.JLabel jLabelDNI;
    private javax.swing.JLabel jLabelDireccion;
    private javax.swing.JLabel jLabelEtiqueta;
    private javax.swing.JLabel jLabelMultiple;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelSingle;
    private javax.swing.JLabel jLabelTelefono;
    private javax.swing.JList<String> jList1;
    private javax.swing.JList<String> jListSingle;
    private javax.swing.JPanel jPanelBotonesCentro;
    private javax.swing.JPanel jPanelCentro;
    private javax.swing.JPanel jPanelNorte;
    private javax.swing.JPanel jPanelSur;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPaneMultiple;
    private javax.swing.JTextArea jTextAreaDatos;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextFieldDNI;
    private javax.swing.JTextField jTextFieldDireccion;
    private javax.swing.JTextField jTextFieldTelefono;
    // End of variables declaration//GEN-END:variables
}
